const restaurantData = [
  {
    id: "res1",
    name: "Royal Biryani House",
    cuisine: "Indian, Mughlai",
    rating: "4.3",
    deliveryTime: "30-35",
    priceForTwo: "₹600",
  },
  {
    id: "res2",
    name: "Pizza Palace",
    cuisine: "Italian, American",
    rating: "4.5",
    deliveryTime: "25-30",
    priceForTwo: "₹800",
  },
  {
    id: "res3",
    name: "Dragon's Delight",
    cuisine: "Chinese, Thai",
    rating: "3.8",
    deliveryTime: "20-25",
    priceForTwo: "₹700",
  },
  {
    id: "res4",
    name: "Taco Fiesta",
    cuisine: "Mexican, Tex-Mex",
    rating: "4.7",
    deliveryTime: "15-20",
    priceForTwo: "₹500",
  },
  {
    id: "res5",
    name: "Sushi Sensation",
    cuisine: "Japanese, Seafood",
    rating: "4.8",
    deliveryTime: "40-45",
    priceForTwo: "₹1200",
  },
  {
    id: "res6",
    name: "Burger Barn",
    cuisine: "Fast Food, American",
    rating: "3.2",
    deliveryTime: "20-30",
    priceForTwo: "₹400",
  },
  {
    id: "res7",
    name: "Curry Corner",
    cuisine: "Indian, South Indian",
    rating: "4.6",
    deliveryTime: "35-40",
    priceForTwo: "₹650",
  },
  {
    id: "res8",
    name: "Mediterranean Marvel",
    cuisine: "Greek, Lebanese",
    rating: "2.5",
    deliveryTime: "30-35",
    priceForTwo: "₹750",
  },
  {
    id: "res9",
    name: "The Vegan Spot",
    cuisine: "Vegan, Organic",
    rating: "4.9",
    deliveryTime: "25-30",
    priceForTwo: "₹900",
  },
  {
    id: "res10",
    name: "BBQ Heaven",
    cuisine: "BBQ, Grilled",
    rating: "3.5",
    deliveryTime: "30-40",
    priceForTwo: "₹1100",
  },
  {
    id: "res11",
    name: "Desi Dhaba",
    cuisine: "Indian, Punjabi",
    rating: "4.0",
    deliveryTime: "20-25",
    priceForTwo: "₹550",
  },
  {
    id: "res12",
    name: "Coastal Delights",
    cuisine: "Seafood, Goan",
    rating: "4.4",
    deliveryTime: "40-50",
    priceForTwo: "₹1300",
  },
  {
    id: "res13",
    name: "Ramen Republic",
    cuisine: "Japanese, Ramen",
    rating: "3.7",
    deliveryTime: "25-30",
    priceForTwo: "₹850",
  },
  {
    id: "res14",
    name: "Street Eats",
    cuisine: "Street Food, Snacks",
    rating: "2.0",
    deliveryTime: "10-15",
    priceForTwo: "₹300",
  },
  {
    id: "res15",
    name: "Healthy Bites",
    cuisine: "Healthy, Salad",
    rating: "4.1",
    deliveryTime: "20-30",
    priceForTwo: "₹600",
  },
  {
    id: "res16",
    name: "Momos & More",
    cuisine: "Tibetan, Nepali",
    rating: "3.9",
    deliveryTime: "20-25",
    priceForTwo: "₹450",
  },
  {
    id: "res17",
    name: "Fast & Fresh",
    cuisine: "Continental, Fusion",
    rating: "4.2",
    deliveryTime: "30-35",
    priceForTwo: "₹700",
  },
  {
    id: "res18",
    name: "Budget Bites",
    cuisine: "Budget, Street Food",
    rating: "1.5",
    deliveryTime: "15-20",
    priceForTwo: "₹200",
  },
  {
    id: "res19",
    name: "Kebab King",
    cuisine: "Middle Eastern, Indian",
    rating: "4.6",
    deliveryTime: "30-40",
    priceForTwo: "₹950",
  },
  {
    id: "res20",
    name: "Gourmet Feast",
    cuisine: "Fine Dining, Multi-cuisine",
    rating: "5.0",
    deliveryTime: "50-60",
    priceForTwo: "₹1500",
  },
];

export default restaurantData;
